import pool from "../config/database.js";

class Employee {
  // ====================================
  // Helper: Check if string is UUID
  // ====================================
  static isUUID(str) {
    if (!str) return false;
    return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
      str
    );
  }

  // ====================================
  // GET ALL (with filters)
  // filters: { department, role, isActive }
  // role is numeric FK (user_roles.id)
  // ====================================
  static async findAll(filters) {
    let query = `
    SELECT 
      e.*,
      d.name AS department_name,
      ur.name AS role_name
    FROM employees e
    LEFT JOIN departments d ON e.department = d.id
    LEFT JOIN user_roles ur ON e.role = ur.id
    WHERE 1=1
  `;
    const params = [];

    if (filters.department) {
      params.push(filters.department);
      query += ` AND e.department = $${params.length}`;
    }

    if (filters.role) {
      params.push(filters.role);
      query += ` AND e.role = $${params.length}`;
    }

    if (filters.isActive !== undefined) {
      params.push(!!filters.isActive);
      query += ` AND e.is_active = $${params.length}`;
    }

    query += ` ORDER BY e.created_at DESC`;

    const result = await pool.query(query, params);
    return result.rows;
  }

  // ====================================
  // GET BY ID
  // Accepts either employee_id (UUID) OR employee_code (string)
  // If value looks like UUID -> match employee_id
  // else                     -> match employee_code
  // ====================================
  static async findById(identifier) {
    if (!identifier) return null;

    const isUUID = this.isUUID(identifier);
    const column = isUUID ? "employee_id" : "employee_code";

    const result = await pool.query(
      `SELECT * FROM employees WHERE ${column} = $1`,
      [identifier]
    );

    return result.rows[0];
  }

  // ====================================
  // GET BY EMAIL
  // ====================================
  static async findByEmail(email) {
    if (!email) return null;

    const result = await pool.query(
      "SELECT * FROM employees WHERE email = $1",
      [email]
    );

    return result.rows[0];
  }

  // ====================================
  // CREATE
  // data is expected to contain:
  //   employee_code (human id, e.g. "EMP-001")
  //   first_name, last_name, email, password_hash
  //   role (FK to user_roles.id), department (FK to departments.id)
  //   designation, reporting_manager_id (UUID or null), doj
  // employee_id is generated by DB (gen_random_uuid)
  // ====================================
  static async create(data) {
    const {
      employee_code,
      first_name,
      last_name,
      email,
      password_hash,
      role,
      department,
      designation,
      reporting_manager_id, // logical name in app
      doj,
    } = data;

    // Validate that reporting_manager_id is a UUID (controller should convert it)
    if (reporting_manager_id && !this.isUUID(reporting_manager_id)) {
      throw new Error(
        `reporting_manager_id must be a UUID, got: ${reporting_manager_id}. ` +
          `Please convert employee_code to UUID in controller before calling create().`
      );
    }

    // Use DB default for employee_id (UUID); map reporting_manager_id -> module_manager_id column
    const result = await pool.query(
      `
      INSERT INTO employees (
        employee_code,
        first_name,
        last_name,
        email,
        password_hash,
        role,
        department,
        designation,
        module_manager_id,
        doj,
        is_active
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,TRUE)
      RETURNING *
      `,
      [
        employee_code,
        first_name,
        last_name,
        email,
        password_hash,
        role,
        department,
        designation,
        reporting_manager_id || null,
        doj,
      ]
    );

    return result.rows[0];
  }

  // ====================================
  // UPDATE
  // Accepts identifier as UUID (employee_id) or employee_code
  // ====================================
  static async update(identifier, data) {
    if (!identifier) throw new Error("ID is required for update");

    // Validate that reporting_manager_id is a UUID if provided
    if (data.reporting_manager_id && !this.isUUID(data.reporting_manager_id)) {
      throw new Error(
        `reporting_manager_id must be a UUID, got: ${data.reporting_manager_id}. ` +
          `Please convert employee_code to UUID in controller before calling update().`
      );
    }

    const fields = [];
    const values = [];
    let paramCount = 1;

    // Map logical field -> DB column if needed
    const payload = { ...data };
    if (payload.reporting_manager_id !== undefined) {
      payload.module_manager_id = payload.reporting_manager_id;
      delete payload.reporting_manager_id;
    }

    Object.keys(payload).forEach((key) => {
      if (payload[key] !== undefined) {
        fields.push(`${key} = $${paramCount}`);
        values.push(payload[key]);
        paramCount++;
      }
    });

    if (fields.length === 0) return await this.findById(identifier);

    fields.push("updated_at = NOW()");
    values.push(identifier);

    const isUUID = this.isUUID(identifier);
    const column = isUUID ? "employee_id" : "employee_code";

    const query = `UPDATE employees SET ${fields.join(
      ", "
    )} WHERE ${column} = $${paramCount} RETURNING *`;

    const result = await pool.query(query, values);

    if (result.rows.length === 0) {
      throw new Error(`Employee with ${column} = ${identifier} not found`);
    }

    return result.rows[0];
  }

  // ====================================
  // DELETE (soft delete)
  // Accepts UUID (employee_id) or employee_code
  // ====================================
  static async delete(identifier) {
    if (!identifier) throw new Error("ID is required for delete");

    const isUUID = this.isUUID(identifier);
    const column = isUUID ? "employee_id" : "employee_code";

    const result = await pool.query(
      `
      UPDATE employees
      SET is_active = FALSE, updated_at = NOW()
      WHERE ${column} = $1
      RETURNING *
      `,
      [identifier]
    );

    if (result.rows.length === 0) {
      throw new Error(`Employee with ${column} = ${identifier} not found`);
    }

    return result.rows[0];
  }

  // ====================================
  // GET UUID FROM employee_code
  // (method name kept for compatibility with existing calls)
  // - if param is already UUID -> returns it
  // - otherwise expects employee_code and returns employee_id (UUID)
  // ====================================
  static async getUUIDFromEmployeeId(employeeId) {
    if (!employeeId) return null;

    // If already a UUID, return it
    if (this.isUUID(employeeId)) {
      return employeeId;
    }

    // Lookup UUID from employee_code
    const result = await pool.query(
      "SELECT employee_id FROM employees WHERE employee_code = $1 AND is_active = TRUE",
      [employeeId]
    );

    if (result.rows.length === 0) {
      throw new Error(
        `Employee with employee_code "${employeeId}" not found or inactive`
      );
    }

    return result.rows[0].employee_id;
  }

  // ====================================
  // GET employee_code FROM UUID
  // - if param is not UUID -> assumes it is already an employee_code
  // ====================================
  static async getEmployeeIdFromUUID(uuid) {
    if (!uuid) return null;

    // If not a UUID, assume it's already an employee_code
    if (!this.isUUID(uuid)) {
      return uuid;
    }

    const result = await pool.query(
      "SELECT employee_code FROM employees WHERE employee_id = $1 AND is_active = TRUE",
      [uuid]
    );

    if (result.rows.length === 0) {
      throw new Error(`Employee with UUID "${uuid}" not found or inactive`);
    }

    return result.rows[0].employee_code;
  }

  // ====================================
  // BATCH GET: managers (for dropdowns)
  // Uses user_roles table to resolve MANAGER role
  // ====================================
  static async findManagers() {
    const result = await pool.query(
      `
      SELECT
        e.employee_id,
        e.employee_code,
        e.first_name || ' ' || e.last_name AS manager_name,
        e.department
      FROM employees e
      JOIN user_roles ur ON ur.id = e.role
      WHERE ur.name = 'MANAGER' AND e.is_active = TRUE
      ORDER BY e.first_name ASC
      `
    );
    return result.rows;
  }

  static async findByDepartment(department) {
    if (!department) return [];

    const result = await pool.query(
      `
      SELECT * FROM employees
      WHERE department = $1 AND is_active = TRUE
      ORDER BY first_name ASC
      `,
      [department]
    );

    return result.rows;
  }

  static async findByReportingManager(managerId) {
    if (!managerId) return [];

    // Convert to UUID if needed (accepts employee_code or UUID)
    const managerUUID = await this.getUUIDFromEmployeeId(managerId);

    const result = await pool.query(
      `
      SELECT * FROM employees
      WHERE module_manager_id = $1 AND is_active = TRUE
      ORDER BY first_name ASC
      `,
      [managerUUID]
    );

    return result.rows;
  }
}

export default Employee;
